"""Distribution-preserving view-noise experiments and frozen v0 utilities.

The covariance/spectral/nested/diagnostic APIs are the formal experiment
surface. The older Sobol, mismatched low-pass, and state-projection APIs stay
exported for backward compatibility and failure reproduction only.
"""

from .covariance import (
    DEFAULT_LOWRANK_TREE_WEIGHTS,
    azimuths_to_slots,
    calibrate_alpha_for_target_kl,
    covariance_metadata,
    identity_mix_covariance,
    is_positive_semidefinite,
    joint_gaussian_kl,
    joint_kl_divergence,
    minimum_eigenvalue,
    mix_covariance_with_identity,
    periodic_camera_rbf_covariance,
    single_tree_covariance,
    stable_cholesky,
    staggered_two_tree_covariance,
    tree_a_covariance,
    tree_ab_covariance,
    tree_b_covariance,
    tree_covariance_from_azimuths,
    validate_covariance_matrix,
)
from .basis import (
    BasisMetadata,
    basis_checksum,
    build_dct2_basis,
    make_dct2_basis,
    ordered_dct2_modes,
)
from .diagnostics import (
    DEFAULT_DISTRIBUTION_THRESHOLDS,
    DEFAULT_LOWRANK_GATE_THRESHOLDS,
    assert_distribution_gates,
    coarse_radial_psd_deviation,
    cross_view_covariance_error,
    cross_view_radial_frequency_correlation,
    diagnose_latents,
    diagnose_lowrank_latents,
    empirical_basis_coefficient_covariance,
    empirical_cross_view_covariance,
    empirical_view_covariance,
    evaluate_distribution_gates,
    evaluate_lowrank_distribution_gates,
    lag_autocorrelations,
    moment_statistics,
    per_view_axis_stripe_scores,
    per_view_lag_autocorrelations,
    per_view_moment_statistics,
    per_view_radial_psd_deviation,
    project_basis_coefficients as project_diagnostic_basis_coefficients,
    radial_power_spectrum,
    radial_psd_deviation,
    spectral_axis_stripe_score,
)
from .lowrank_coupling import (
    CouplingMetadata,
    SUPPORTED_COUPLING_METHODS,
    apply_latent_coupling,
    correlate_orthonormal_subspace,
    make_shared_full_latents,
)
from .trajectory import (
    DEFAULT_TRAJECTORY_MILESTONES,
    NILETrajectoryObserver,
    TRAJECTORY_SCHEMA_VERSION,
    TrajectoryObserver,
    TrajectorySnapshot,
    coefficient_view_correlation,
    compute_paired_delta,
    load_trajectory_npz,
    milestone_label,
    milestone_step_indices,
    project_basis_coefficients as project_trajectory_basis_coefficients,
    save_paired_delta,
)
from .nested_elements import (
    angles_to_dyadic_slots,
    element_seed_key,
    frequency_dependent_level_weights,
    make_nested_tree_latents,
    nested_tree_spatial_covariance_target,
    tree_ancestor_ids,
)
from .spectral_gaussian import (
    camera_rbf_spatial_covariance_target,
    global_spatial_covariance_target,
    make_camera_rbf_correlated_latents,
    make_spectral_global_correlated_latents,
    radial_frequency_grid,
    spectral_correlation_profile,
)

from .callbacks import (
    CallbackMode,
    NILECallbackConfig,
    NILEViewTimeCallback,
    build_patch_rho_map,
    linear_rho,
)
from .morton import morton2d, part1by1, patch_morton_order
from .ops import gaussian_blur_latent, low_high_split, standardize_like, standardize_unit
from .sampler import (
    NILEConfig,
    SamplerMode,
    make_flat_sobol_latents,
    make_iid_latents,
    make_initial_latents,
    make_lowpass_shared_latents,
    make_nile_v_latents,
    make_shared_latents,
)
from .sequence import SZBackend, SobolBackend, inverse_normal_cdf


__all__ = [
    "BasisMetadata",
    "CallbackMode",
    "CouplingMetadata",
    "DEFAULT_DISTRIBUTION_THRESHOLDS",
    "DEFAULT_LOWRANK_GATE_THRESHOLDS",
    "DEFAULT_LOWRANK_TREE_WEIGHTS",
    "DEFAULT_TRAJECTORY_MILESTONES",
    "NILECallbackConfig",
    "NILEConfig",
    "NILEViewTimeCallback",
    "NILETrajectoryObserver",
    "SUPPORTED_COUPLING_METHODS",
    "SZBackend",
    "SamplerMode",
    "SobolBackend",
    "TRAJECTORY_SCHEMA_VERSION",
    "TrajectoryObserver",
    "TrajectorySnapshot",
    "apply_latent_coupling",
    "angles_to_dyadic_slots",
    "assert_distribution_gates",
    "azimuths_to_slots",
    "basis_checksum",
    "build_dct2_basis",
    "build_patch_rho_map",
    "camera_rbf_spatial_covariance_target",
    "coarse_radial_psd_deviation",
    "coefficient_view_correlation",
    "compute_paired_delta",
    "correlate_orthonormal_subspace",
    "cross_view_covariance_error",
    "cross_view_radial_frequency_correlation",
    "diagnose_latents",
    "diagnose_lowrank_latents",
    "element_seed_key",
    "empirical_cross_view_covariance",
    "empirical_basis_coefficient_covariance",
    "empirical_view_covariance",
    "evaluate_distribution_gates",
    "evaluate_lowrank_distribution_gates",
    "frequency_dependent_level_weights",
    "gaussian_blur_latent",
    "inverse_normal_cdf",
    "is_positive_semidefinite",
    "joint_gaussian_kl",
    "joint_kl_divergence",
    "lag_autocorrelations",
    "linear_rho",
    "low_high_split",
    "make_flat_sobol_latents",
    "make_iid_latents",
    "make_initial_latents",
    "make_dct2_basis",
    "make_lowpass_shared_latents",
    "make_camera_rbf_correlated_latents",
    "make_nested_tree_latents",
    "make_nile_v_latents",
    "make_shared_latents",
    "make_shared_full_latents",
    "make_spectral_global_correlated_latents",
    "minimum_eigenvalue",
    "mix_covariance_with_identity",
    "identity_mix_covariance",
    "covariance_metadata",
    "calibrate_alpha_for_target_kl",
    "moment_statistics",
    "morton2d",
    "part1by1",
    "patch_morton_order",
    "load_trajectory_npz",
    "milestone_label",
    "milestone_step_indices",
    "nested_tree_spatial_covariance_target",
    "per_view_axis_stripe_scores",
    "per_view_lag_autocorrelations",
    "per_view_moment_statistics",
    "per_view_radial_psd_deviation",
    "project_diagnostic_basis_coefficients",
    "project_trajectory_basis_coefficients",
    "periodic_camera_rbf_covariance",
    "radial_frequency_grid",
    "radial_power_spectrum",
    "radial_psd_deviation",
    "single_tree_covariance",
    "save_paired_delta",
    "spectral_axis_stripe_score",
    "spectral_correlation_profile",
    "stable_cholesky",
    "staggered_two_tree_covariance",
    "standardize_like",
    "standardize_unit",
    "tree_ancestor_ids",
    "tree_a_covariance",
    "tree_ab_covariance",
    "tree_b_covariance",
    "tree_covariance_from_azimuths",
    "ordered_dct2_modes",
    "validate_covariance_matrix",
    "global_spatial_covariance_target",
]
